# datos_otm.py

otm_detalle_data = [
    {
        "numero": "OTM001",
        "fecha": "2025-07-20",
        "servicio": "Cardiología",
        "equipo": "Electrocardiógrafo",
        "firma_licenciada": False ,
        "marca": "Philips",
        "modelo": "ECG2000",
        "serie": "PH123456",
        "codigo": "EQ-001",
        "falla": "No enciende",
        "solicita": "Dr. Pérez",
        "cargo": "Jefe de Servicio",
        "fecha_solicitud": "2025-07-19",
        "estado": "Por archivar",
        "acciones": "Cambio de fusible y revisión general",
        "responsable": "Técnico Ramírez",
        "fecha_ejecucion": "2025-07-21",
        "observaciones": "Equipo operativo",
        "costo_total": "350.00",
        "materiales": "Fusible 2A, cable",
        "mano_obra": "150.00"
    },
    {
        "numero": "OTM002",
        "fecha": "2025-07-18",
        "servicio": "Emergencia",
        "equipo": "Monitor de signos vitales",
        "firma_licenciada": False ,
        "marca": "GE",
        "modelo": "B40",
        "serie": "GE987654",
        "codigo": "EQ-002",
        "falla": "Pantalla parpadea",
        "solicita": "Enf. Rodríguez",
        "cargo": "Jefe de Turno",
        "fecha_solicitud": "2025-07-17",
        "estado": "Por archivar",
        "acciones": "Cambio de pantalla LCD",
        "responsable": "Téc. Gutiérrez",
        "fecha_ejecucion": "2025-07-19",
        "observaciones": "Pruebas satisfactorias",
        "costo_total": "480.00",
        "materiales": "Pantalla LCD",
        "mano_obra": "200.00"
    },
    {
        "numero": "OTM003",
        "fecha": "2025-07-19",
        "servicio": "Pediatría",
        "equipo": "Incubadora",
        "firma_licenciada": False ,
        "marca": "Draeger",
        "modelo": "Isolette",
        "serie": "DR456123",
        "codigo": "EQ-003",
        "falla": "No regula temperatura",
        "solicita": "Dr. Suárez",
        "cargo": "Neonatólogo",
        "fecha_solicitud": "2025-07-18",
        "estado": "Por archivar",
        "acciones": "Cambio de termostato",
        "responsable": "Ing. Palacios",
        "fecha_ejecucion": "2025-07-20",
        "observaciones": "Revisión periódica recomendada",
        "costo_total": "620.00",
        "materiales": "Termostato",
        "mano_obra": "250.00"
    },
    {
        "numero": "OTM004",
        "fecha": "2025-07-15",
        "servicio": "Laboratorio",
        "equipo": "Centrífuga",
        "firma_licenciada": False ,
        "marca": "Eppendorf",
        "modelo": "5702R",
        "serie": "EP234789",
        "codigo": "EQ-004",
        "falla": "Hace ruido al girar",
        "solicita": "Quím. Romero",
        "cargo": "Analista",
        "fecha_solicitud": "2025-07-14",
        "estado": "Por archivar",
        "acciones": "Lubricación y cambio de rodamientos",
        "responsable": "Téc. Herrera",
        "fecha_ejecucion": "2025-07-16",
        "observaciones": "Reducción significativa de ruido",
        "costo_total": "310.00",
        "materiales": "Rodamientos",
        "mano_obra": "120.00"
    },
    {
        "numero": "OTM005",
        "fecha": "2025-07-12",
        "servicio": "Rayos X",
        "equipo": "Reveladora de placas",
        "firma_licenciada": False ,
        "marca": "Agfa",
        "modelo": "CR30-X",
        "serie": "AG874563",
        "codigo": "EQ-005",
        "falla": "Error de escaneo",
        "solicita": "Téc. Alarcón",
        "cargo": "Radiólogo",
        "fecha_solicitud": "2025-07-11",
        "estado": "Por archivar",
        "acciones": "Reconfiguración del software",
        "responsable": "Ing. Torres",
        "fecha_ejecucion": "2025-07-13",
        "observaciones": "Software actualizado",
        "costo_total": "150.00",
        "materiales": "N/A",
        "mano_obra": "150.00"
    },

    {
        "numero": "OTM006",
        "fecha": "2025-07-14",
        "servicio": "Ecografía",
        "equipo": "Ecógrafo portátil",
        "firma_licenciada": False ,
        "marca": "Philips",
        "modelo": "CX50",
        "serie": "PH569321",
        "codigo": "EQ-006",
        "falla": "Pantalla sin imagen",
        "solicita": "Téc. Herrera",
        "cargo": "Tecnólogo Médico",
        "fecha_solicitud": "2025-07-13",
        "estado": "Por archivar",
        "acciones": "Cambio de cable HDMI interno",
        "responsable": "Ing. Ríos",
        "fecha_ejecucion": "2025-07-15",
        "observaciones": "Equipo operativo tras prueba",
        "costo_total": "220.00",
        "materiales": "Cable HDMI",
        "mano_obra": "180.00"
    },
    {
        "numero": "OTM007",
        "fecha": "2025-07-15",
        "servicio": "Laboratorio",
        "equipo": "Centrífuga de sangre",
        "firma_licenciada": False ,
        "marca": "Eppendorf",
        "modelo": "5702R",
        "serie": "EP004512",
        "codigo": "EQ-007",
        "falla": "No enciende",
        "solicita": "Téc. Guzmán",
        "cargo": "Bioquímico",
        "fecha_solicitud": "2025-07-14",
        "estado": "Por archivar",
        "acciones": "Revisión de la fuente de alimentación",
        "responsable": "Ing. Silva",
        "fecha_ejecucion": "2025-07-16",
        "observaciones": "Pendiente de cambio de fuente",
        "costo_total": "160.00",
        "materiales": "Fuente 24V",
        "mano_obra": "120.00"
    },
    {
        "numero": "OTM008",
        "fecha": "2025-07-16",
        "servicio": "Cardiología",
        "equipo": "Electrocardiógrafo",
        "firma_licenciada": False ,
        "marca": "GE Healthcare",
        "modelo": "MAC 2000",
        "serie": "GE802156",
        "codigo": "EQ-008",
        "falla": "Lectura errónea de señales",
        "solicita": "Dr. Cáceres",
        "cargo": "Cardiólogo",
        "fecha_solicitud": "2025-07-15",
        "estado": "Por archivar",
        "acciones": "Calibración de electrodos",
        "responsable": "Ing. Vargas",
        "fecha_ejecucion": "2025-07-17",
        "observaciones": "Funcionamiento correcto tras calibración",
        "costo_total": "90.00",
        "materiales": "N/A",
        "mano_obra": "90.00"
    },
    {
        "numero": "OTM009",
        "fecha": "2025-07-17",
        "servicio": "Endoscopía",
        "equipo": "Colonoscopio",
        "firma_licenciada": False ,
        "marca": "Olympus",
        "modelo": "CF-H190",
        "serie": "OL234899",
        "codigo": "EQ-009",
        "falla": "Obstrucción del canal de succión",
        "solicita": "Téc. Ramírez",
        "cargo": "Endoscopista",
        "fecha_solicitud": "2025-07-16",
        "estado": "Por archivar",
        "acciones": "Limpieza profunda y prueba funcional",
        "responsable": "Ing. Fuentes",
        "fecha_ejecucion": "2025-07-18",
        "observaciones": "Canal despejado y operativo",
        "costo_total": "130.00",
        "materiales": "Solución enzimática",
        "mano_obra": "100.00"
    },
    {
        "numero": "OTM010",
        "fecha": "2025-07-18",
        "servicio": "Tomografía",
        "equipo": "Tomógrafo axial",
        "firma_licenciada": False ,
        "marca": "Siemens",
        "modelo": "SOMATOM Definition",
        "serie": "SI100731",
        "codigo": "EQ-010",
        "falla": "Error de calibración",
        "solicita": "Dr. Beltrán",
        "cargo": "Radiólogo",
        "fecha_solicitud": "2025-07-17",
        "estado": "Por archivar",
        "acciones": "Calibración completa de sistema",
        "responsable": "Ing. Chávez",
        "fecha_ejecucion": "2025-07-19",
        "observaciones": "Calibrado conforme a protocolo",
        "costo_total": "300.00",
        "materiales": "N/A",
        "mano_obra": "300.00"
    },

    {
        "numero": "OTM011",
        "fecha": "2025-07-19",
        "servicio": "Oftalmología",
        "equipo": "Retinógrafo digital",
        "firma_licenciada": False ,
        "marca": "Topcon",
        "modelo": "TRC-NW400",
        "serie": "TP112998",
        "codigo": "EQ-011",
        "falla": "Imagen borrosa",
        "solicita": "Dra. Vega",
        "cargo": "Oftalmóloga",
        "fecha_solicitud": "2025-07-18",
        "estado": "Por archivar",
        "acciones": "Revisión de enfoque automático",
        "responsable": "Ing. Moreno",
        "fecha_ejecucion": "2025-07-20",
        "observaciones": "Calibración satisfactoria",
        "costo_total": "95.00",
        "materiales": "N/A",
        "mano_obra": "95.00"
    },
    {
        "numero": "OTM012",
        "fecha": "2025-07-20",
        "servicio": "Urgencias",
        "equipo": "Monitor multiparámetro",
        "firma_licenciada": False ,
        "marca": "Mindray",
        "modelo": "iMEC10",
        "serie": "MD381264",
        "codigo": "EQ-012",
        "falla": "Alarma sin causa aparente",
        "solicita": "Téc. Linares",
        "cargo": "Enfermero",
        "fecha_solicitud": "2025-07-19",
        "estado": "Por archivar",
        "acciones": "Reset de sistema y verificación de sensores",
        "responsable": "Ing. Paredes",
        "fecha_ejecucion": "2025-07-21",
        "observaciones": "Alarmas normalizadas",
        "costo_total": "120.00",
        "materiales": "N/A",
        "mano_obra": "120.00"
    },
    {
        "numero": "OTM013",
        "fecha": "2025-07-21",
        "servicio": "Hemodiálisis",
        "equipo": "Máquina de diálisis",
        "firma_licenciada": False ,
        "marca": "Fresenius",
        "modelo": "4008S",
        "serie": "FR902371",
        "codigo": "EQ-013",
        "falla": "Presión de filtro alta",
        "solicita": "Téc. Flores",
        "cargo": "Nefrólogo",
        "fecha_solicitud": "2025-07-20",
        "estado": "Por archivar",
        "acciones": "Cambio de filtro y limpieza de bomba",
        "responsable": "Ing. Quispe",
        "fecha_ejecucion": "2025-07-22",
        "observaciones": "Presión dentro de rango",
        "costo_total": "210.00",
        "materiales": "Filtro hemodiálisis",
        "mano_obra": "150.00"
    },
    {
        "numero": "OTM014",
        "fecha": "2025-07-22",
        "servicio": "Neonatología",
        "equipo": "Incubadora neonatal",
        "firma_licenciada": False ,
        "marca": "Dräger",
        "modelo": "Isolette C2000",
        "serie": "DR110987",
        "codigo": "EQ-014",
        "falla": "Falla en regulación térmica",
        "solicita": "Téc. Cabrera",
        "cargo": "Pediatra",
        "fecha_solicitud": "2025-07-21",
        "estado": "Por archivar",
        "acciones": "Reemplazo de termistor",
        "responsable": "Ing. Zambrano",
        "fecha_ejecucion": "2025-07-23",
        "observaciones": "Temperatura estable",
        "costo_total": "180.00",
        "materiales": "Termistor",
        "mano_obra": "140.00"
    },
    {
        "numero": "OTM015",
        "fecha": "2025-07-23",
        "servicio": "Radiología",
        "equipo": "Digitalizador CR",
        "firma_licenciada": False ,
        "marca": "Carestream",
        "modelo": "Vita Flex",
        "serie": "CS847611",
        "codigo": "EQ-015",
        "falla": "No detecta placas",
        "solicita": "Téc. Ramírez",
        "cargo": "Radiólogo",
        "fecha_solicitud": "2025-07-22",
        "estado": "Por archivar",
        "acciones": "Revisión del lector óptico",
        "responsable": "Ing. Hidalgo",
        "fecha_ejecucion": "2025-07-24",
        "observaciones": "Sensor ajustado correctamente",
        "costo_total": "145.00",
        "materiales": "N/A",
        "mano_obra": "145.00"
    },
    {
        "numero": "OTM016",
        "fecha": "2025-07-24",
        "servicio": "Farmacia",
        "equipo": "Refrigerador biomédico",
        "firma_licenciada": False ,
        "marca": "Labcold",
        "modelo": "RLDF0219",
        "serie": "LB394872",
        "codigo": "EQ-016",
        "falla": "Temperatura inestable",
        "solicita": "Téc. Gallardo",
        "cargo": "Farmacéutico",
        "fecha_solicitud": "2025-07-23",
        "estado": "Por archivar",
        "acciones": "Cambio de termostato",
        "responsable": "Ing. Salas",
        "fecha_ejecucion": "2025-07-25",
        "observaciones": "Rango térmico estabilizado",
        "costo_total": "200.00",
        "materiales": "Termostato digital",
        "mano_obra": "160.00"
    },
    {
        "numero": "OTM017",
        "fecha": "2025-07-25",
        "servicio": "Laboratorio clínico",
        "equipo": "Analizador hematológico",
        "firma_licenciada": False ,
        "marca": "Sysmex",
        "modelo": "XN-1000",
        "serie": "SY557219",
        "codigo": "EQ-017",
        "falla": "Obstrucción en tubo de muestras",
        "solicita": "Téc. Farfán",
        "cargo": "Bioquímico",
        "fecha_solicitud": "2025-07-24",
        "estado": "Por archivar",
        "acciones": "Desobstrucción mecánica",
        "responsable": "Ing. Correa",
        "fecha_ejecucion": "2025-07-26",
        "observaciones": "Flujo de muestra normalizado",
        "costo_total": "110.00",
        "materiales": "Tubo de repuesto",
        "mano_obra": "80.00"
    },
    {
        "numero": "OTM018",
        "fecha": "2025-07-26",
        "servicio": "Imagenología",
        "equipo": "Arco en C",
        "firma_licenciada": False ,
        "marca": "Ziehm",
        "modelo": "Vision R",
        "serie": "ZH789650",
        "codigo": "EQ-018",
        "falla": "Error de movimiento en eje vertical",
        "solicita": "Téc. Poma",
        "cargo": "Radiólogo",
        "fecha_solicitud": "2025-07-25",
        "estado": "Por archivar",
        "acciones": "Lubricación y ajuste mecánico",
        "responsable": "Ing. Tapia",
        "fecha_ejecucion": "2025-07-27",
        "observaciones": "Movimiento fluido confirmado",
        "costo_total": "175.00",
        "materiales": "Lubricante médico",
        "mano_obra": "140.00"
    },
    {
        "numero": "OTM019",
        "fecha": "2025-07-27",
        "servicio": "UCI",
        "equipo": "Respirador mecánico",
        "firma_licenciada": False ,
        "marca": "Hamilton",
        "modelo": "C1",
        "serie": "HM734265",
        "codigo": "EQ-019",
        "falla": "Alerta de volumen insuficiente",
        "solicita": "Téc. Valverde",
        "cargo": "Intensivista",
        "fecha_solicitud": "2025-07-26",
        "estado": "Por archivar",
        "acciones": "Calibración de flujo de aire",
        "responsable": "Ing. Vidal",
        "fecha_ejecucion": "2025-07-28",
        "observaciones": "Flujo dentro de parámetros clínicos",
        "costo_total": "190.00",
        "materiales": "N/A",
        "mano_obra": "190.00"
    },
   
{
    "numero": "OTM020",
    "fecha": "2025-07-28",
    "servicio": "Ginecología",
    "equipo": "Ecógrafo transvaginal",
    "firma_licenciada": False ,
    "marca": "Samsung",
    "modelo": "HS40",
    "serie": "SS839274",
    "codigo": "EQ-020",
    "falla": "Desincronización de imagen",
    "solicita": "Dra. Loayza",
    "cargo": "Ginecóloga",
    "fecha_solicitud": "2025-07-27",
    "estado": "Por archivar",
    "acciones": "Actualización de firmware",
    "responsable": "Ing. Aranda",
    "fecha_ejecucion": "2025-07-29",
    "observaciones": "Sincronización verificada",
    "costo_total": "185.00",
    "materiales": "N/A",
    "mano_obra": "185.00"
}



]

# Puedes continuar con el mismo formato hasta el OTM-020
