# datos_otm.py

otm_detalle_data = [
    {
        "numero": "OTM001",
        "fecha": "2025-07-20",
        "servicio": "Cardiología",
        "equipo": "Electrocardiógrafo",
        "marca": "Philips",
        "modelo": "ECG2000",
        "serie": "PH123456",
        "codigo": "EQ-001",
        "falla": "No enciende",
        "solicita": "Dr. Pérez",
        "cargo": "Jefe de Servicio",
        "fecha_solicitud": "2025-07-19",
        "estado": "Por archivar",
        "acciones": "Cambio de fusible y revisión general",
        "responsable": "Técnico Ramírez",
        "fecha_ejecucion": "2025-07-21",
        "observaciones": "Equipo operativo",
        "costo_total": "350.00",
        "materiales": "Fusible 2A, cable",
        "mano_obra": "150.00"
    },
    {
        "numero": "OTM002",
        "fecha": "2025-07-18",
        "servicio": "Emergencia",
        "equipo": "Monitor de signos vitales",
        "marca": "GE",
        "modelo": "B40",
        "serie": "GE987654",
        "codigo": "EQ-002",
        "falla": "Pantalla parpadea",
        "solicita": "Enf. Rodríguez",
        "cargo": "Jefe de Turno",
        "fecha_solicitud": "2025-07-17",
        "estado": "Por archivar",
        "acciones": "Cambio de pantalla LCD",
        "responsable": "Téc. Gutiérrez",
        "fecha_ejecucion": "2025-07-19",
        "observaciones": "Pruebas satisfactorias",
        "costo_total": "480.00",
        "materiales": "Pantalla LCD",
        "mano_obra": "200.00"
    },
    {
        "numero": "OTM003",
        "fecha": "2025-07-19",
        "servicio": "Pediatría",
        "equipo": "Incubadora",
        "marca": "Draeger",
        "modelo": "Isolette",
        "serie": "DR456123",
        "codigo": "EQ-003",
        "falla": "No regula temperatura",
        "solicita": "Dr. Suárez",
        "cargo": "Neonatólogo",
        "fecha_solicitud": "2025-07-18",
        "estado": "Por archivar",
        "acciones": "Cambio de termostato",
        "responsable": "Ing. Palacios",
        "fecha_ejecucion": "2025-07-20",
        "observaciones": "Revisión periódica recomendada",
        "costo_total": "620.00",
        "materiales": "Termostato",
        "mano_obra": "250.00"
    },
    {
        "numero": "OTM004",
        "fecha": "2025-07-15",
        "servicio": "Laboratorio",
        "equipo": "Centrífuga",
        "marca": "Eppendorf",
        "modelo": "5702R",
        "serie": "EP234789",
        "codigo": "EQ-004",
        "falla": "Hace ruido al girar",
        "solicita": "Quím. Romero",
        "cargo": "Analista",
        "fecha_solicitud": "2025-07-14",
        "estado": "Por archivar",
        "acciones": "Lubricación y cambio de rodamientos",
        "responsable": "Téc. Herrera",
        "fecha_ejecucion": "2025-07-16",
        "observaciones": "Reducción significativa de ruido",
        "costo_total": "310.00",
        "materiales": "Rodamientos",
        "mano_obra": "120.00"
    },
    {
        "numero": "OTM005",
        "fecha": "2025-07-12",
        "servicio": "Rayos X",
        "equipo": "Reveladora de placas",
        "marca": "Agfa",
        "modelo": "CR30-X",
        "serie": "AG874563",
        "codigo": "EQ-005",
        "falla": "Error de escaneo",
        "solicita": "Téc. Alarcón",
        "cargo": "Radiólogo",
        "fecha_solicitud": "2025-07-11",
        "estado": "Por archivar",
        "acciones": "Reconfiguración del software",
        "responsable": "Ing. Torres",
        "fecha_ejecucion": "2025-07-13",
        "observaciones": "Software actualizado",
        "costo_total": "150.00",
        "materiales": "N/A",
        "mano_obra": "150.00"
    },
    # Continúan hasta el 20:
]

# Puedes continuar con el mismo formato hasta el OTM-020
